import React from 'react';
import '../static/css/PvMiles.css';

function PvMiles() {
  return (
    <div className="pv-miles-background">
      <div className="split pv-miles-textbox">
        <div className="pv-squish-text">
          <p className="pv-text pv-text-regular">
            The amount of clean, green energy generated by PV4EV in 1 year is enough to drive a passenger vehicle
          </p>
          <p style={{ marginTop: '80px', marginBottom: '90px' }} className="pv-text pv-text-huge">
            23,710
          </p>
          <p className="pv-text pv-text-big">MILES</p>
          <p style={{ marginTop: '-20px' }} className="pv-text pv-text-regular">
            Almost all the way around the Earth!
          </p>
        </div>
      </div>
    </div>
  );
}

export default PvMiles;
